# Phiên bản Docker Compose
version: '3.8'

# Định nghĩa các service
services:
  # Service backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/warehouse_db?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password

  # Service frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  # Service MySQL
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=warehouse_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

# Định nghĩa volume để lưu trữ dữ liệu MySQL
volumes:
  mysql-data:
